services:
  accounts:
    image: "vinaysteja0231/accounts:v2.2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - travelbank
  loans:
    image: "vinaysteja0231/loans:v2.2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - travelbank
  cards:
    image: "vinaysteja0231/cards:v2.2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - travelbank
networks:
  travelbank:
    driver: "bridge"